# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Creator',
            new_name='creator',
        ),
    ]
