# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0002_auto_20160624_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskItem', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='taskItems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToDoList.Item'),
        ),
    ]
