# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0005_remove_item_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='taskItems',
        ),
        migrations.AddField(
            model_name='item',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ToDoList.Task'),
        ),
    ]
